name = "astro-tarot-realm"
account_id = "ba1d688671ae99c51095e2ad24945f77"
compatibility_date = "2026-03-24"
compatibility_flags = ["nodejs_compat"]
main = ".open-next/_worker.js"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "astro-tarot-db"
database_id = "a7d11bd2-73e7-4ea1-870f-62af80838d74"

[ai]
binding = "AI"

[triggers]
crons = ["0 2 * * *"]
