export default function TermsPage() {
  return (
    <main className="min-h-screen px-6 py-16 max-w-3xl mx-auto">
      <div className="text-center mb-12">
        <div className="text-gold text-sm tracking-[0.3em] uppercase font-cinzel mb-4">✦ Legal ✦</div>
        <h1 className="font-cinzel text-4xl font-bold text-textMain">Terms of Service</h1>
        <p className="text-textSub mt-3 text-sm">Last updated: March 27, 2026</p>
      </div>

      <div className="space-y-8 text-textSub leading-relaxed">

        <section>
          <h2 className="font-cinzel text-xl font-semibold text-textMain mb-3">1. Acceptance of Terms</h2>
          <p>By accessing and using TarotRealm.xyz ("the Service"), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the Service.</p>
        </section>

        <section>
          <h2 className="font-cinzel text-xl font-semibold text-textMain mb-3">2. Description of Service</h2>
          <p>TarotRealm provides AI-powered tarot card readings and horoscope interpretations for entertainment purposes only. All readings are generated by artificial intelligence and are not intended to be taken as factual predictions, professional advice, or guidance for life decisions.</p>
        </section>

        <section>
          <h2 className="font-cinzel text-xl font-semibold text-textMain mb-3">3. User Accounts</h2>
          <p className="mb-2">To access certain features, you may sign in using your Google account. You are responsible for:</p>
          <ul className="list-disc list-inside space-y-1 ml-2">
            <li>Maintaining the security of your account</li>
            <li>All activities that occur under your account</li>
            <li>Providing accurate information</li>
          </ul>
        </section>

        <section>
          <h2 className="font-cinzel text-xl font-semibold text-textMain mb-3">4. Subscription Plans & Payments</h2>
          <p className="mb-2">We offer the following plans:</p>
          <ul className="list-disc list-inside space-y-1 ml-2 mb-3">
            <li><strong className="text-textMain">Free:</strong> 3 readings per day, 7-day history</li>
            <li><strong className="text-textMain">Pro Monthly:</strong> $3.99/month — Unlimited readings, full history, 10 deep readings/day</li>
            <li><strong className="text-textMain">Pro Yearly:</strong> $29.99/year — Same as Monthly, save 37%</li>
          </ul>
          <p>Payments are processed securely by PayPal. We do not store your payment information.</p>
        </section>

        <section>
          <h2 className="font-cinzel text-xl font-semibold text-textMain mb-3">5. Refund Policy</h2>
          <div className="rounded-xl p-4 mb-3" style={{ backgroundColor: 'rgba(155,89,182,0.1)', border: '1px solid rgba(155,89,182,0.3)' }}>
            <p className="text-textMain font-semibold mb-2">✦ 7-Day Money-Back Guarantee</p>
            <p>If you are not satisfied with your Pro subscription, you may request a full refund within <strong className="text-textMain">7 days</strong> of your purchase date.</p>
          </div>
          <p className="mb-2"><strong className="text-textMain">Refund conditions:</strong></p>
          <ul className="list-disc list-inside space-y-1 ml-2">
            <li>Refund must be requested within 7 days of purchase</li>
            <li>Each account is eligible for <strong className="text-textMain">one refund only</strong></li>
            <li>Subsequent purchases are non-refundable</li>
            <li>To request a refund, contact us at: <a href="mailto:support@tarotrealm.xyz" className="text-primary hover:underline">support@tarotrealm.xyz</a></li>
          </ul>
          <p className="mt-3 text-sm">Upon approved refund, your account will be downgraded to the Free plan immediately.</p>
        </section>

        <section>
          <h2 className="font-cinzel text-xl font-semibold text-textMain mb-3">6. Disclaimer</h2>
          <p>TarotRealm is for <strong className="text-textMain">entertainment purposes only</strong>. The AI-generated readings are not a substitute for professional advice (medical, legal, financial, psychological, or otherwise). We make no guarantees about the accuracy or reliability of any reading.</p>
        </section>

        <section>
          <h2 className="font-cinzel text-xl font-semibold text-textMain mb-3">7. Prohibited Use</h2>
          <p className="mb-2">You agree not to:</p>
          <ul className="list-disc list-inside space-y-1 ml-2">
            <li>Use the Service for any unlawful purpose</li>
            <li>Attempt to abuse the free tier limits through automated means</li>
            <li>Resell or redistribute content generated by the Service</li>
            <li>Interfere with or disrupt the Service</li>
          </ul>
        </section>

        <section>
          <h2 className="font-cinzel text-xl font-semibold text-textMain mb-3">8. Changes to Terms</h2>
          <p>We reserve the right to modify these Terms at any time. Continued use of the Service after changes constitutes acceptance of the new Terms.</p>
        </section>

        <section>
          <h2 className="font-cinzel text-xl font-semibold text-textMain mb-3">9. Contact</h2>
          <p>For questions or refund requests, contact us at: <a href="mailto:support@tarotrealm.xyz" className="text-primary hover:underline">support@tarotrealm.xyz</a></p>
        </section>

      </div>
    </main>
  )
}
